# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: meroxa
builds:
- env:
  - CGO_ENABLED=0
  flags:
  - -mod=vendor
  goos:
  - darwin
  - linux
  - windows
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
brews:
  - tap:
      owner: meroxa
      name: homebrew-taps
    folder: Formula
    homepage:  https://meroxa.io
    description: The Meroxa CLI
    license: "Apache 2.0"
    custom_block: |
      head "https://github.com/meroxa/cli.git"
    test: |
      shell_output("#{bin}/meroxa version").match(/{{ replace .Tag "v" "" }}/)
    dependencies:
    - name: go
    install: |-
      bin.install "meroxa"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  prerelease: true
