project_name: meroxa
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
    main: cmd/meroxa/main.go
    goos:
      - darwin
      - linux
      - windows
archives:
  - files:
      - etc/*
      - LICENSE
      - README.md
      - docs/*
brews:
  - tap:
      owner: meroxa
      name: homebrew-taps
    commit_author:
      name: meroxa-machine
      email: machine@meroxa.io
    folder: Formula
    homepage:  https://meroxa.io
    description: The Meroxa CLI
    license: "Apache 2.0"
    custom_block: |
      head "https://github.com/meroxa/cli.git"
    test: |
      shell_output("#{bin}/meroxa version").match(/{{ replace .Tag "v" "" }}/)
    install: |-
      bin.install "meroxa"
      prefix.install_metafiles
      bash_completion.install "etc/completion/meroxa.completion.sh"
      zsh_completion.install "etc/completion/meroxa.completion.zsh" => "meroxa"
      fish_completion.install "etc/completion/meroxa.completion.fish"
      man.install "etc/man/man1"
scoop:
  bucket:
    owner: meroxa
    name: scoop_manifests
    branch: main
  folder: meroxa
  homepage:  https://meroxa.io
  description: The Meroxa CLI
  license: "Apache 2.0"
  commit_author:
      name: meroxa-machine
      email: machine@meroxa.io
  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'