# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.16
        environment:
          GO111MODULE: "on"
          GOPATH: "/go"
    working_directory: /go/src/github.com/meroxa/cli
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "16:26:c9:af:c0:c6:27:08:be:31:b5:36:40:71:63:44"

      # lock in authentication for Github modules via ssh
      - run: git config --global --add url."git@github.com:".insteadOf "https://github.com/"

      # disable checksum checking via Go on private Meroxa repositories
      - run: go env -w GOPRIVATE=github.com/meroxa/*

      # specify any bash command here prefixed with `run: `
      - run: go test -mod=vendor -v -race ./...
