.nh
.TH "Meroxa" "1" "Aug 2021" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa\-config\-describe \- Show Meroxa CLI configuration details


.SH SYNOPSIS
.PP
\fBmeroxa config describe [flags]\fP


.SH DESCRIPTION
.PP
Show Meroxa CLI configuration details


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for describe


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-config\fP=""
	config file

.PP
\fB\-\-debug\fP[=false]
	display any debugging information

.PP
\fB\-\-json\fP[=false]
	output json

.PP
\fB\-\-timeout\fP=10s
	set the duration of the client timeout in seconds (default 10s)


.SH SEE ALSO
.PP
\fBmeroxa\-config(1)\fP
