.nh
.TH "Meroxa" "1" "Apr 2023" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa-auth - Authentication commands for Meroxa


.SH SYNOPSIS
.PP
\fBmeroxa auth [flags]\fP


.SH DESCRIPTION
.PP
Authentication commands for Meroxa


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for auth


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--cli-config-file\fP=""
	meroxa configuration file

.PP
\fB--debug\fP[=false]
	display any debugging information

.PP
\fB--json\fP[=false]
	output json

.PP
\fB--timeout\fP=10s
	set the duration of the client timeout in seconds


.SH SEE ALSO
.PP
\fBmeroxa(1)\fP, \fBmeroxa-auth-login(1)\fP, \fBmeroxa-auth-logout(1)\fP, \fBmeroxa-auth-whoami(1)\fP
