.nh
.TH "Meroxa" "1" "Oct 2022" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa-apps-deploy - Deploy a Turbine Data Application (Beta)


.SH SYNOPSIS
.PP
\fBmeroxa apps deploy [flags]\fP


.SH DESCRIPTION
.PP
This command will deploy the application specified in '--path'
(or current working directory if not specified) to our Meroxa Platform.
If deployment was successful, you should expect an application you'll be able to fully manage


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for deploy

.PP
\fB--path\fP=""
	Path to the app directory (default is local directory)

.PP
\fB--skip-collection-validation\fP[=false]
	Skips unique destination collection and looping validations


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--cli-config-file\fP=""
	meroxa configuration file

.PP
\fB--debug\fP[=false]
	display any debugging information

.PP
\fB--json\fP[=false]
	output json

.PP
\fB--timeout\fP=10s
	set the duration of the client timeout in seconds


.SH EXAMPLE
.PP
.RS

.nf
meroxa apps deploy # assumes you run it from the app directory
meroxa apps deploy --path ./my-app


.fi
.RE


.SH SEE ALSO
.PP
\fBmeroxa-apps(1)\fP
