.nh
.TH "Meroxa" "1" "Sep 2021" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa\-connectors\-update \- Update connector name, configuration or state


.SH SYNOPSIS
.PP
\fBmeroxa connectors update NAME \-\-state pause | resume | restart \-\-name new\-name \-\-config new\-configuration [flags]\fP


.SH DESCRIPTION
.PP
Update connector name, configuration or state


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for update

.PP
\fB\-\-name\fP=""
	new connector name

.PP
\fB\-\-state\fP=""
	new connector state


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-config\fP=""
	config file

.PP
\fB\-\-debug\fP[=false]
	display any debugging information

.PP
\fB\-\-json\fP[=false]
	output json

.PP
\fB\-\-timeout\fP=10s
	set the duration of the client timeout in seconds (default 10s)


.SH EXAMPLE
.PP
.RS

.nf

meroxa connector update old\-name \-\-name new\-name' 
meroxa connector update connector\-name \-\-state pause' 
meroxa connector update connector\-name \-\-config '{"table.name.format":"public.copy"}' 


.fi
.RE


.SH SEE ALSO
.PP
\fBmeroxa\-connectors(1)\fP
