.nh
.TH "Meroxa" "1" "Dec 2022" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa-environments - Manage environments on Meroxa


.SH SYNOPSIS
.PP
\fBmeroxa environments [flags]\fP


.SH DESCRIPTION
.PP
Manage environments on Meroxa


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for environments


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--cli-config-file\fP=""
	meroxa configuration file

.PP
\fB--debug\fP[=false]
	display any debugging information

.PP
\fB--json\fP[=false]
	output json

.PP
\fB--timeout\fP=10s
	set the duration of the client timeout in seconds


.SH SEE ALSO
.PP
\fBmeroxa(1)\fP, \fBmeroxa-environments-create(1)\fP, \fBmeroxa-environments-describe(1)\fP, \fBmeroxa-environments-list(1)\fP, \fBmeroxa-environments-remove(1)\fP, \fBmeroxa-environments-repair(1)\fP, \fBmeroxa-environments-update(1)\fP
