.nh
.TH "Meroxa" "1" "Feb 2024" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa-secrets-list - List all Conduit Secrets


.SH SYNOPSIS
.PP
\fBmeroxa secrets list [--path pwd] [flags]\fP


.SH DESCRIPTION
.PP
This command will list all the secrets defined on the platform.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for list


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--api-url\fP=""
	API url

.PP
\fB--cli-config-file\fP=""
	meroxa configuration file

.PP
\fB--debug\fP[=false]
	display any debugging information

.PP
\fB--json\fP[=false]
	output json

.PP
\fB--timeout\fP=10s
	set the duration of the client timeout in seconds


.SH EXAMPLE
.EX
meroxa secrets list

.EE


.SH SEE ALSO
.PP
\fBmeroxa-secrets(1)\fP
