.nh
.TH "Meroxa" "1" "Aug 2022" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa\-config \- Manage your Meroxa CLI configuration


.SH SYNOPSIS
.PP
\fBmeroxa config [flags]\fP


.SH DESCRIPTION
.PP
Manage your Meroxa CLI configuration


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for config


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-cli\-config\-file\fP=""
	meroxa configuration file

.PP
\fB\-\-debug\fP[=false]
	display any debugging information

.PP
\fB\-\-json\fP[=false]
	output json

.PP
\fB\-\-timeout\fP=10s
	set the duration of the client timeout in seconds


.SH SEE ALSO
.PP
\fBmeroxa(1)\fP, \fBmeroxa\-config\-describe(1)\fP, \fBmeroxa\-config\-set(1)\fP
