.nh
.TH "Meroxa" "1" "Mar 2022" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa\-environments\-update \- Update an environment


.SH SYNOPSIS
.PP
\fBmeroxa environments update NAMEorUUID [flags]\fP


.SH DESCRIPTION
.PP
Update an environment


.SH OPTIONS
.PP
\fB\-c\fP, \fB\-\-config\fP=[]
	updated environment configuration based on type and provider (e.g.: \-\-config aws\_access\_key\_id=my\_access\_key \-\-config aws\_access\_secret=my\_access\_secret)

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for update

.PP
\fB\-\-name\fP=""
	updated environment name, when specified

.PP
\fB\-y\fP, \fB\-\-yes\fP[=false]
	skip confirmation prompt


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-cli\-config\-file\fP=""
	meroxa configuration file

.PP
\fB\-\-debug\fP[=false]
	display any debugging information

.PP
\fB\-\-json\fP[=false]
	output json

.PP
\fB\-\-timeout\fP=10s
	set the duration of the client timeout in seconds


.SH EXAMPLE
.PP
.RS

.nf

meroxa env update my\-env \-\-name new\-name \-\-config aws\_access\_key\_id=my\_access\_key \-\-config aws\_access\_secret=my\_access\_secret"


.fi
.RE


.SH SEE ALSO
.PP
\fBmeroxa\-environments(1)\fP
