.nh
.TH "Meroxa" "1" "Apr 2021" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa\-logs\-connector \- Print logs for a connector


.SH SYNOPSIS
.PP
\fBmeroxa logs connector NAME [flags]\fP


.SH DESCRIPTION
.PP
Print logs for a connector


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for connector


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-config\fP=""
	config file (default is $HOME/meroxa.env)

.PP
\fB\-\-debug\fP[=false]
	display any debugging information

.PP
\fB\-\-json\fP[=false]
	output json


.SH SEE ALSO
.PP
\fBmeroxa\-logs(1)\fP
