.nh
.TH "Meroxa" "1" "Nov 2021" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa\-pipelines \- Manage pipelines on Meroxa


.SH SYNOPSIS
.PP
\fBmeroxa pipelines [flags]\fP


.SH DESCRIPTION
.PP
Manage pipelines on Meroxa


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for pipelines


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-cli\-config\-file\fP=""
	meroxa configuration file

.PP
\fB\-\-debug\fP[=false]
	display any debugging information

.PP
\fB\-\-json\fP[=false]
	output json

.PP
\fB\-\-timeout\fP=10s
	set the duration of the client timeout in seconds


.SH SEE ALSO
.PP
\fBmeroxa(1)\fP, \fBmeroxa\-pipelines\-create(1)\fP, \fBmeroxa\-pipelines\-list(1)\fP, \fBmeroxa\-pipelines\-remove(1)\fP, \fBmeroxa\-pipelines\-update(1)\fP
