.nh
.TH "Meroxa" "1" "Jan 2022" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa\-auth\-login \- Login or Sign up to the Meroxa Platform


.SH SYNOPSIS
.PP
\fBmeroxa auth login [flags]\fP


.SH DESCRIPTION
.PP
Login or Sign up to the Meroxa Platform


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for login


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-cli\-config\-file\fP=""
	meroxa configuration file

.PP
\fB\-\-debug\fP[=false]
	display any debugging information

.PP
\fB\-\-json\fP[=false]
	output json

.PP
\fB\-\-timeout\fP=10s
	set the duration of the client timeout in seconds


.SH SEE ALSO
.PP
\fBmeroxa\-auth(1)\fP
