.nh
.TH "Meroxa" "1" "Nov 2023" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa-apps-open - Open the link to a Turbine Data Application in the Dashboard


.SH SYNOPSIS
.PP
\fBmeroxa apps open [--path pwd] [flags]\fP


.SH DESCRIPTION
.PP
Open the link to a Turbine Data Application in the Dashboard


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for open

.PP
\fB--path\fP=""
	Path to the app directory (default is local directory)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--api-url\fP=""
	API url

.PP
\fB--cli-config-file\fP=""
	meroxa configuration file

.PP
\fB--debug\fP[=false]
	display any debugging information

.PP
\fB--json\fP[=false]
	output json

.PP
\fB--timeout\fP=10s
	set the duration of the client timeout in seconds


.SH EXAMPLE
.PP
.RS

.nf
meroxa apps open # assumes that the Application is in the current directory
meroxa apps open --path /my/app
meroxa apps open NAMEorUUID

.fi
.RE


.SH SEE ALSO
.PP
\fBmeroxa-apps(1)\fP
