.nh
.TH "Meroxa" "1" "Oct 2022" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa-project-set - Set active project


.SH SYNOPSIS
.PP
\fBmeroxa project set [flags]\fP


.SH DESCRIPTION
.PP
Set active project


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for set


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--cli-config-file\fP=""
	meroxa configuration file

.PP
\fB--debug\fP[=false]
	display any debugging information

.PP
\fB--json\fP[=false]
	output json

.PP
\fB--timeout\fP=10s
	set the duration of the client timeout in seconds


.SH SEE ALSO
.PP
\fBmeroxa-project(1)\fP
