.nh
.TH "Meroxa" "1" "Oct 2023" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa-apps-upgrade - Upgrade a Turbine Data Application


.SH SYNOPSIS
.PP
\fBmeroxa apps upgrade [--path pwd] [flags]\fP


.SH DESCRIPTION
.PP
Upgrade a Turbine Data Application


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for upgrade

.PP
\fB--path\fP=""
	path where application exists (current directory as default)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--cli-config-file\fP=""
	meroxa configuration file

.PP
\fB--debug\fP[=false]
	display any debugging information

.PP
\fB--json\fP[=false]
	output json

.PP
\fB--timeout\fP=10s
	set the duration of the client timeout in seconds


.SH EXAMPLE
.PP
.RS

.nf
meroxa apps upgrade --path ~/code

.fi
.RE


.SH SEE ALSO
.PP
\fBmeroxa-apps(1)\fP
