.nh
.TH "Meroxa" "1" "Jan 2022" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa\-environments\-create \- Create an environment


.SH SYNOPSIS
.PP
\fBmeroxa environments create NAME [flags]\fP


.SH DESCRIPTION
.PP
Create an environment


.SH OPTIONS
.PP
\fB\-c\fP, \fB\-\-config\fP=[]
	environment configuration based on type and provider (e.g.: \-\-config aws\_access\_key\_id=my\_access\_key \-\-config aws\_access\_secret=my\_access\_secret)

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for create

.PP
\fB\-\-provider\fP=""
	environment cloud provider to use

.PP
\fB\-\-region\fP=""
	environment region

.PP
\fB\-\-type\fP=""
	environment type, when not specified

.PP
\fB\-y\fP, \fB\-\-yes\fP[=false]
	skip confirmation prompt


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-cli\-config\-file\fP=""
	meroxa configuration file

.PP
\fB\-\-debug\fP[=false]
	display any debugging information

.PP
\fB\-\-json\fP[=false]
	output json

.PP
\fB\-\-timeout\fP=10s
	set the duration of the client timeout in seconds


.SH EXAMPLE
.PP
.RS

.nf

meroxa env create my\-env \-\-type self\_hosted \-\-provider aws \-\-region us\-east\-1 \-\-config aws\_access\_key\_id=my\_access\_key \-\-config aws\_access\_secret=my\_access\_secret


.fi
.RE


.SH SEE ALSO
.PP
\fBmeroxa\-environments(1)\fP
