.nh
.TH "Meroxa" "1" "May 2023" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa-apps-describe - Describe a Turbine Data Application


.SH SYNOPSIS
.PP
\fBmeroxa apps describe [NameOrUUID] [--path pwd] [flags]\fP


.SH DESCRIPTION
.PP
This command will fetch details about the Application specified in '--path'
(or current working directory if not specified) on our Meroxa Platform,
or the Application specified by the given name or UUID identifier.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for describe

.PP
\fB--path\fP=""
	Path to the app directory (default is local directory)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--cli-config-file\fP=""
	meroxa configuration file

.PP
\fB--debug\fP[=false]
	display any debugging information

.PP
\fB--json\fP[=false]
	output json

.PP
\fB--timeout\fP=10s
	set the duration of the client timeout in seconds


.SH EXAMPLE
.PP
.RS

.nf
meroxa apps describe # assumes that the Application is in the current directory
meroxa apps describe --path /my/app
meroxa apps describe NAMEorUUID

.fi
.RE


.SH SEE ALSO
.PP
\fBmeroxa-apps(1)\fP
