.nh
.TH "Meroxa" "1" "Feb 2023" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa-apps-list - List Turbine Data Applications (Beta)


.SH SYNOPSIS
.PP
\fBmeroxa apps list [flags]\fP


.SH DESCRIPTION
.PP
List Turbine Data Applications (Beta)


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for list

.PP
\fB--no-headers\fP[=false]
	display output without headers


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--cli-config-file\fP=""
	meroxa configuration file

.PP
\fB--debug\fP[=false]
	display any debugging information

.PP
\fB--json\fP[=false]
	output json

.PP
\fB--timeout\fP=10s
	set the duration of the client timeout in seconds


.SH SEE ALSO
.PP
\fBmeroxa-apps(1)\fP
