.nh
.TH "Meroxa" "1" "Apr 2022" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa\-connectors\-logs \- Print logs for a connector


.SH SYNOPSIS
.PP
\fBmeroxa connectors logs NAME [flags]\fP


.SH DESCRIPTION
.PP
Print logs for a connector


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for logs


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-cli\-config\-file\fP=""
	meroxa configuration file

.PP
\fB\-\-debug\fP[=false]
	display any debugging information

.PP
\fB\-\-json\fP[=false]
	output json

.PP
\fB\-\-timeout\fP=10s
	set the duration of the client timeout in seconds


.SH SEE ALSO
.PP
\fBmeroxa\-connectors(1)\fP
