.nh
.TH "Meroxa" "1" "Apr 2022" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa\-apps \- Manage Meroxa Data Applications


.SH SYNOPSIS
.PP
\fBmeroxa apps [flags]\fP


.SH DESCRIPTION
.PP
Manage Meroxa Data Applications


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for apps


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-cli\-config\-file\fP=""
	meroxa configuration file

.PP
\fB\-\-debug\fP[=false]
	display any debugging information

.PP
\fB\-\-json\fP[=false]
	output json

.PP
\fB\-\-timeout\fP=10s
	set the duration of the client timeout in seconds


.SH SEE ALSO
.PP
\fBmeroxa(1)\fP, \fBmeroxa\-apps\-deploy(1)\fP, \fBmeroxa\-apps\-describe(1)\fP, \fBmeroxa\-apps\-init(1)\fP, \fBmeroxa\-apps\-list(1)\fP, \fBmeroxa\-apps\-remove(1)\fP, \fBmeroxa\-apps\-run(1)\fP
