.nh
.TH "Meroxa" "1" "Apr 2021" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa\-list\-resource\-types \- List resource\-types


.SH SYNOPSIS
.PP
\fBmeroxa list resource\-types [flags]\fP


.SH DESCRIPTION
.PP
List resource\-types


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for resource\-types


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-config\fP=""
	config file (default is $HOME/meroxa.env)

.PP
\fB\-\-debug\fP[=false]
	display any debugging information

.PP
\fB\-\-json\fP[=false]
	output json


.SH SEE ALSO
.PP
\fBmeroxa\-list(1)\fP
