.nh
.TH "Meroxa" "1" "Jul 2021" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa\-resources\-validate \- Validate a resource


.SH SYNOPSIS
.PP
\fBmeroxa resources validate NAME [flags]\fP


.SH DESCRIPTION
.PP
Validate a Meroxa resource.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for validate


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-config\fP=""
	config file

.PP
\fB\-\-debug\fP[=false]
	display any debugging information

.PP
\fB\-\-json\fP[=false]
	output json

.PP
\fB\-\-timeout\fP=10s
	set the client timeout


.SH SEE ALSO
.PP
\fBmeroxa\-resources(1)\fP
