.nh
.TH "Meroxa" "1" "Aug 2023" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa-resources-list - List resources and resource types


.SH SYNOPSIS
.PP
\fBmeroxa resources list [flags]\fP


.SH DESCRIPTION
.PP
List resources and resource types


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for list

.PP
\fB--no-headers\fP[=false]
	display output without headers

.PP
\fB--types\fP[=false]
	list resource types


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--cli-config-file\fP=""
	meroxa configuration file

.PP
\fB--debug\fP[=false]
	display any debugging information

.PP
\fB--json\fP[=false]
	output json

.PP
\fB--timeout\fP=10s
	set the duration of the client timeout in seconds


.SH SEE ALSO
.PP
\fBmeroxa-resources(1)\fP
