.nh
.TH "Meroxa" "1" "Feb 2024" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa-secrets-remove - Remove a Turbine Secret


.SH SYNOPSIS
.PP
\fBmeroxa secrets remove [--path pwd] [flags]\fP


.SH DESCRIPTION
.PP
This command will remove the secret specified either by name or id


.SH OPTIONS
.PP
\fB-f\fP, \fB--force\fP[=false]
	skip confirmation

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for remove


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--api-url\fP=""
	API url

.PP
\fB--cli-config-file\fP=""
	meroxa configuration file

.PP
\fB--debug\fP[=false]
	display any debugging information

.PP
\fB--json\fP[=false]
	output json

.PP
\fB--timeout\fP=10s
	set the duration of the client timeout in seconds


.SH EXAMPLE
.EX
meroxa apps remove nameOrUUID

.EE


.SH SEE ALSO
.PP
\fBmeroxa-secrets(1)\fP
