.nh
.TH "Meroxa" "1" "Oct 2022" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa-apps-remove - Removes a Turbine Data Application (Beta)


.SH SYNOPSIS
.PP
\fBmeroxa apps remove NAME [flags]\fP


.SH DESCRIPTION
.PP
Removes a Turbine Data Application (Beta)


.SH OPTIONS
.PP
\fB-f\fP, \fB--force\fP[=false]
	skip confirmation

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for remove


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--cli-config-file\fP=""
	meroxa configuration file

.PP
\fB--debug\fP[=false]
	display any debugging information

.PP
\fB--json\fP[=false]
	output json

.PP
\fB--timeout\fP=10s
	set the duration of the client timeout in seconds


.SH SEE ALSO
.PP
\fBmeroxa-apps(1)\fP
