.nh
.TH "Meroxa" "1" "Apr 2021" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa\-list\-connectors \- List connectors


.SH SYNOPSIS
.PP
\fBmeroxa list connectors [flags]\fP


.SH DESCRIPTION
.PP
List connectors


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for connectors

.PP
\fB\-\-pipeline\fP=""
	filter connectors by pipeline name


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-config\fP=""
	config file (default is $HOME/meroxa.env)

.PP
\fB\-\-debug\fP[=false]
	display any debugging information

.PP
\fB\-\-json\fP[=false]
	output json


.SH SEE ALSO
.PP
\fBmeroxa\-list(1)\fP
