.nh
.TH "Meroxa" "1" "Feb 2023" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa-apps-logs - View relevant logs to the state of the given Turbine Data Application (Beta)


.SH SYNOPSIS
.PP
\fBmeroxa apps logs [NameOrUUID] [--path pwd] [flags]\fP


.SH DESCRIPTION
.PP
This command will fetch relevant logs about the Application specified in '--path'
(or current working directory if not specified) on our Meroxa Platform,
or the Application specified by the given name or UUID identifier.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for logs

.PP
\fB--path\fP=""
	Path to the app directory (default is local directory)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--cli-config-file\fP=""
	meroxa configuration file

.PP
\fB--debug\fP[=false]
	display any debugging information

.PP
\fB--json\fP[=false]
	output json

.PP
\fB--timeout\fP=10s
	set the duration of the client timeout in seconds


.SH EXAMPLE
.PP
.RS

.nf
meroxa apps logs # assumes that the Application is in the current directory
meroxa apps logs --path /my/app
meroxa apps logs my-turbine-application

.fi
.RE


.SH SEE ALSO
.PP
\fBmeroxa-apps(1)\fP
