.nh
.TH "Meroxa" "1" "Oct 2023" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa-apps-remove - Remove a Turbine Data Application


.SH SYNOPSIS
.PP
\fBmeroxa apps remove [NameOrUUID] [--path pwd] [flags]\fP


.SH DESCRIPTION
.PP
This command will remove the Application specified in '--path'
(or current working directory if not specified) previously deployed on our Meroxa Platform,
or the Application specified by the given name or UUID identifier.


.SH OPTIONS
.PP
\fB-f\fP, \fB--force\fP[=false]
	skip confirmation

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for remove

.PP
\fB--path\fP=""
	Path to the app directory (default is local directory)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--cli-config-file\fP=""
	meroxa configuration file

.PP
\fB--debug\fP[=false]
	display any debugging information

.PP
\fB--json\fP[=false]
	output json

.PP
\fB--timeout\fP=10s
	set the duration of the client timeout in seconds


.SH EXAMPLE
.PP
.RS

.nf
meroxa apps remove # assumes that the Application is in the current directory
meroxa apps remove --path /my/app
meroxa apps remove NAME

.fi
.RE


.SH SEE ALSO
.PP
\fBmeroxa-apps(1)\fP
