.nh
.TH "Meroxa" "1" "Aug 2022" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa\-apps\-logs \- View relevant logs to the state of the given Turbine Data Application (Beta)


.SH SYNOPSIS
.PP
\fBmeroxa apps logs [NAMEorUUID] [flags]\fP


.SH DESCRIPTION
.PP
View relevant logs to the state of the given Turbine Data Application (Beta)


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for logs


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-cli\-config\-file\fP=""
	meroxa configuration file

.PP
\fB\-\-debug\fP[=false]
	display any debugging information

.PP
\fB\-\-json\fP[=false]
	output json

.PP
\fB\-\-timeout\fP=10s
	set the duration of the client timeout in seconds


.SH EXAMPLE
.PP
.RS

.nf
meroxa apps logs my\-turbine\-application

.fi
.RE


.SH SEE ALSO
.PP
\fBmeroxa\-apps(1)\fP
