.nh
.TH "Meroxa" "1" "Apr 2021" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa\-add \- Add a resource to your Meroxa resource catalog


.SH SYNOPSIS
.PP
\fBmeroxa add [flags]\fP


.SH DESCRIPTION
.PP
Add a resource to your Meroxa resource catalog


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for add


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-config\fP=""
	config file (default is $HOME/meroxa.env)

.PP
\fB\-\-debug\fP[=false]
	display any debugging information

.PP
\fB\-\-json\fP[=false]
	output json


.SH SEE ALSO
.PP
\fBmeroxa(1)\fP, \fBmeroxa\-add\-resource(1)\fP
