.nh
.TH "Meroxa" "1" "Jul 2021" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa\-connectors\-update \- Update connector state


.SH SYNOPSIS
.PP
\fBmeroxa connectors update NAME \-\-state pause | resume | restart [flags]\fP


.SH DESCRIPTION
.PP
Update connector state


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for update

.PP
\fB\-\-state\fP=""
	connector state


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-config\fP=""
	config file

.PP
\fB\-\-debug\fP[=false]
	display any debugging information

.PP
\fB\-\-json\fP[=false]
	output json

.PP
\fB\-\-timeout\fP=10s
	set the client timeout


.SH SEE ALSO
.PP
\fBmeroxa\-connectors(1)\fP
