.nh
.TH "Meroxa" "1" "Oct 2022" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa-apps-run - Execute a Turbine Data Application locally (Beta)


.SH SYNOPSIS
.PP
\fBmeroxa apps run [flags]\fP


.SH DESCRIPTION
.PP
meroxa apps run will build your app locally to then run it locally in --path.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for run

.PP
\fB--path\fP=""
	path of application to run


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--cli-config-file\fP=""
	meroxa configuration file

.PP
\fB--debug\fP[=false]
	display any debugging information

.PP
\fB--json\fP[=false]
	output json

.PP
\fB--timeout\fP=10s
	set the duration of the client timeout in seconds


.SH EXAMPLE
.PP
.RS

.nf
meroxa apps run 			# assumes you run it from the app directory
meroxa apps run --path ../go-demo 	# it'll use lang defined in your app.json


.fi
.RE


.SH SEE ALSO
.PP
\fBmeroxa-apps(1)\fP
