.nh
.TH "Meroxa" "1" "Apr 2021" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa\-update\-resource \- Update a resource


.SH SYNOPSIS
.PP
\fBmeroxa update resource NAME [flags]\fP


.SH DESCRIPTION
.PP
Use the update command to update various Meroxa resources.


.SH OPTIONS
.PP
\fB\-\-credentials\fP=""
	resource credentials

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for resource

.PP
\fB\-m\fP, \fB\-\-metadata\fP=""
	resource metadata

.PP
\fB\-u\fP, \fB\-\-url\fP=""
	resource url


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-config\fP=""
	config file (default is $HOME/meroxa.env)

.PP
\fB\-\-debug\fP[=false]
	display any debugging information

.PP
\fB\-\-json\fP[=false]
	output json


.SH SEE ALSO
.PP
\fBmeroxa\-update(1)\fP
