.nh
.TH "Meroxa" "1" "Aug 2022" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa\-resources\-remove \- Remove resource


.SH SYNOPSIS
.PP
\fBmeroxa resources remove NAME [flags]\fP


.SH DESCRIPTION
.PP
Remove resource


.SH OPTIONS
.PP
\fB\-f\fP, \fB\-\-force\fP[=false]
	skip confirmation

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for remove


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-cli\-config\-file\fP=""
	meroxa configuration file

.PP
\fB\-\-debug\fP[=false]
	display any debugging information

.PP
\fB\-\-json\fP[=false]
	output json

.PP
\fB\-\-timeout\fP=10s
	set the duration of the client timeout in seconds


.SH SEE ALSO
.PP
\fBmeroxa\-resources(1)\fP
