.nh
.TH "Meroxa" "1" "Feb 2024" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa-auth-whoami - Display the current logged in user


.SH SYNOPSIS
.PP
\fBmeroxa auth whoami [flags]\fP


.SH DESCRIPTION
.PP
Display the current logged in user


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for whoami


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--api-url\fP=""
	API url

.PP
\fB--cli-config-file\fP=""
	meroxa configuration file

.PP
\fB--debug\fP[=false]
	display any debugging information

.PP
\fB--json\fP[=false]
	output json

.PP
\fB--timeout\fP=10s
	set the duration of the client timeout in seconds


.SH EXAMPLE
.EX
meroxa whoami

.EE


.SH SEE ALSO
.PP
\fBmeroxa-auth(1)\fP
