.nh
.TH "Meroxa" "1" "Jun 2021" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa\-resources \- Manage resources on Meroxa


.SH SYNOPSIS
.PP
\fBmeroxa resources [flags]\fP


.SH DESCRIPTION
.PP
Manage resources on Meroxa


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for resources


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-config\fP=""
	config file

.PP
\fB\-\-debug\fP[=false]
	display any debugging information

.PP
\fB\-\-json\fP[=false]
	output json

.PP
\fB\-\-timeout\fP=10s
	set the client timeout


.SH SEE ALSO
.PP
\fBmeroxa(1)\fP, \fBmeroxa\-resources\-create(1)\fP, \fBmeroxa\-resources\-describe(1)\fP, \fBmeroxa\-resources\-list(1)\fP, \fBmeroxa\-resources\-remove(1)\fP, \fBmeroxa\-resources\-update(1)\fP
