.nh
.TH "Meroxa" "1" "Apr 2021" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa\-describe \- Describe a component


.SH SYNOPSIS
.PP
\fBmeroxa describe [flags]\fP


.SH DESCRIPTION
.PP
Describe a component of the Meroxa data platform, including resources and connectors


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for describe


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-config\fP=""
	config file (default is $HOME/meroxa.env)

.PP
\fB\-\-debug\fP[=false]
	display any debugging information

.PP
\fB\-\-json\fP[=false]
	output json


.SH SEE ALSO
.PP
\fBmeroxa(1)\fP, \fBmeroxa\-describe\-connector(1)\fP, \fBmeroxa\-describe\-endpoint(1)\fP, \fBmeroxa\-describe\-resource(1)\fP
