.nh
.TH "Meroxa" "1" "Apr 2021" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa \- The Meroxa CLI


.SH SYNOPSIS
.PP
\fBmeroxa [flags]\fP


.SH DESCRIPTION
.PP
The Meroxa CLI allows quick and easy access to the Meroxa data platform.

.PP
Using the CLI you are able to create and manage sophisticated data pipelines
with only a few simple commands. You can get started by listing the supported
resource types:

.PP
meroxa list resource\-types


.SH OPTIONS
.PP
\fB\-\-config\fP=""
	config file (default is $HOME/meroxa.env)

.PP
\fB\-\-debug\fP[=false]
	display any debugging information

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for meroxa

.PP
\fB\-\-json\fP[=false]
	output json


.SH SEE ALSO
.PP
\fBmeroxa\-add(1)\fP, \fBmeroxa\-api(1)\fP, \fBmeroxa\-billing(1)\fP, \fBmeroxa\-completion(1)\fP, \fBmeroxa\-connect(1)\fP, \fBmeroxa\-create(1)\fP, \fBmeroxa\-describe(1)\fP, \fBmeroxa\-list(1)\fP, \fBmeroxa\-login(1)\fP, \fBmeroxa\-logout(1)\fP, \fBmeroxa\-logs(1)\fP, \fBmeroxa\-open(1)\fP, \fBmeroxa\-remove(1)\fP, \fBmeroxa\-update(1)\fP, \fBmeroxa\-version(1)\fP
