.nh
.TH "Meroxa" "1" "May 2022" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa\-apps\-init \- Initialize a Turbine Data Application (Beta)


.SH SYNOPSIS
.PP
\fBmeroxa apps init [APP\_NAME] [\-\-path pwd] \-\-lang js|go|py [flags]\fP


.SH DESCRIPTION
.PP
Initialize a Turbine Data Application (Beta)


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for init

.PP
\fB\-l\fP, \fB\-\-lang\fP=""
	language to use (js|go|py) (required)

.PP
\fB\-\-mod\-vendor\fP[=false]
	whether to download modules to vendor or globally while initializing a Go application

.PP
\fB\-\-path\fP=""
	path where application will be initialized (current directory as default)

.PP
\fB\-\-skip\-mod\-init\fP[=false]
	whether to run 'go mod init' while initializing a Go application


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-cli\-config\-file\fP=""
	meroxa configuration file

.PP
\fB\-\-debug\fP[=false]
	display any debugging information

.PP
\fB\-\-json\fP[=false]
	output json

.PP
\fB\-\-timeout\fP=10s
	set the duration of the client timeout in seconds


.SH EXAMPLE
.PP
.RS

.nf
meroxa apps init my\-app \-\-path \~/code \-\-lang js
meroxa apps init my\-app \-\-lang py
meroxa apps init my\-app \-\-lang go 			# will be initialized in a dir called my\-app in the current directory
meroxa apps init my\-app \-\-lang go \-\-skip\-mod\-init 	# will not initialize the new go module
meroxa apps init my\-app \-\-lang go \-\-mod\-vendor 		# will initialize the new go module and download dependencies to the vendor directory
meroxa apps init my\-app \-\-lang go \-\-path $GOPATH/src/github.com/my.org


.fi
.RE


.SH SEE ALSO
.PP
\fBmeroxa\-apps(1)\fP
