.nh
.TH "Meroxa" "1" "Apr 2021" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa\-list \- List components


.SH SYNOPSIS
.PP
\fBmeroxa list [flags]\fP


.SH DESCRIPTION
.PP
List the components of the Meroxa platform, including pipelines,
 resources, connectors, etc... You may also filter by type.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for list


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-config\fP=""
	config file (default is $HOME/meroxa.env)

.PP
\fB\-\-debug\fP[=false]
	display any debugging information

.PP
\fB\-\-json\fP[=false]
	output json


.SH SEE ALSO
.PP
\fBmeroxa(1)\fP, \fBmeroxa\-list\-connectors(1)\fP, \fBmeroxa\-list\-endpoint(1)\fP, \fBmeroxa\-list\-pipelines(1)\fP, \fBmeroxa\-list\-resource\-types(1)\fP, \fBmeroxa\-list\-resources(1)\fP, \fBmeroxa\-list\-transforms(1)\fP
