.nh
.TH "Meroxa" "1" "Nov 2023" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa-secrets-update - Update a Turbine Secret


.SH SYNOPSIS
.PP
\fBmeroxa secrets update nameOrUUID --data '{"key": "any new data"} [flags]\fP


.SH DESCRIPTION
.PP
This command will update the specified Turbine Secret's data.


.SH OPTIONS
.PP
\fB--data\fP=""
	Secret's data, passed as a JSON string

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for update


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--api-url\fP=""
	API url

.PP
\fB--cli-config-file\fP=""
	meroxa configuration file

.PP
\fB--debug\fP[=false]
	display any debugging information

.PP
\fB--json\fP[=false]
	output json

.PP
\fB--timeout\fP=10s
	set the duration of the client timeout in seconds


.SH EXAMPLE
.PP
.RS

.nf
meroxa secrets update nameOrUUID --data '{"key": "value"}' 
		or 
		meroxa secrets update nameOrUUID 

.fi
.RE


.SH SEE ALSO
.PP
\fBmeroxa-secrets(1)\fP
