.nh
.TH "Meroxa" "1" "May 2021" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa\-pipelines\-create \- Create a pipeline


.SH SYNOPSIS
.PP
\fBmeroxa pipelines create NAME [flags]\fP


.SH DESCRIPTION
.PP
Create a pipeline


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for create

.PP
\fB\-m\fP, \fB\-\-metadata\fP=""
	pipeline metadata


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-config\fP=""
	config file

.PP
\fB\-\-debug\fP[=false]
	display any debugging information

.PP
\fB\-\-json\fP[=false]
	output json

.PP
\fB\-\-timeout\fP=10s
	set the client timeout


.SH SEE ALSO
.PP
\fBmeroxa\-pipelines(1)\fP
