.nh
.TH "Meroxa" "1" "Apr 2021" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa\-remove \- Remove a component


.SH SYNOPSIS
.PP
\fBmeroxa remove [flags]\fP


.SH DESCRIPTION
.PP
Deprovision a component of the Meroxa platform, including pipelines,
 resources, and connectors


.SH OPTIONS
.PP
\fB\-f\fP, \fB\-\-force\fP[=false]
	force delete without confirmation prompt

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for remove


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-config\fP=""
	config file (default is $HOME/meroxa.env)

.PP
\fB\-\-debug\fP[=false]
	display any debugging information

.PP
\fB\-\-json\fP[=false]
	output json


.SH SEE ALSO
.PP
\fBmeroxa(1)\fP, \fBmeroxa\-remove\-connector(1)\fP, \fBmeroxa\-remove\-endpoint(1)\fP, \fBmeroxa\-remove\-pipeline(1)\fP, \fBmeroxa\-remove\-resource(1)\fP
