.nh
.TH "Meroxa" "1" "Apr 2021" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa\-remove\-endpoint \- Remove endpoint


.SH SYNOPSIS
.PP
\fBmeroxa remove endpoint NAME [flags]\fP


.SH DESCRIPTION
.PP
Remove endpoint


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for endpoint


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-config\fP=""
	config file (default is $HOME/meroxa.env)

.PP
\fB\-\-debug\fP[=false]
	display any debugging information

.PP
\fB\-f\fP, \fB\-\-force\fP[=false]
	force delete without confirmation prompt

.PP
\fB\-\-json\fP[=false]
	output json


.SH SEE ALSO
.PP
\fBmeroxa\-remove(1)\fP
