.nh
.TH "Meroxa" "1" "Mar 2023" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa-environments-describe - Describe environment


.SH SYNOPSIS
.PP
\fBmeroxa environments describe [NAMEorUUID] [flags]\fP


.SH DESCRIPTION
.PP
Describe environment


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for describe


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--cli-config-file\fP=""
	meroxa configuration file

.PP
\fB--debug\fP[=false]
	display any debugging information

.PP
\fB--json\fP[=false]
	output json

.PP
\fB--timeout\fP=10s
	set the duration of the client timeout in seconds


.SH SEE ALSO
.PP
\fBmeroxa-environments(1)\fP
