.nh
.TH "Meroxa" "1" "Jun 2021" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa\-resources\-update \- Update a resource


.SH SYNOPSIS
.PP
\fBmeroxa resources update NAME [flags]\fP


.SH DESCRIPTION
.PP
Use the update command to update various Meroxa resources.


.SH OPTIONS
.PP
\fB\-\-ca\-cert\fP=""
	trusted certificates for verifying resource

.PP
\fB\-\-client\-cert\fP=""
	client certificate for authenticating to the resource

.PP
\fB\-\-client\-key\fP=""
	client private key for authenticating to the resource

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for update

.PP
\fB\-m\fP, \fB\-\-metadata\fP=""
	new resource metadata

.PP
\fB\-\-name\fP=""
	new resource name

.PP
\fB\-\-password\fP=""
	password

.PP
\fB\-\-ssh\-url\fP=""
	SSH tunneling address

.PP
\fB\-\-ssl\fP[=false]
	use SSL

.PP
\fB\-u\fP, \fB\-\-url\fP=""
	new resource url

.PP
\fB\-\-username\fP=""
	username


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-config\fP=""
	config file

.PP
\fB\-\-debug\fP[=false]
	display any debugging information

.PP
\fB\-\-json\fP[=false]
	output json

.PP
\fB\-\-timeout\fP=10s
	set the client timeout


.SH SEE ALSO
.PP
\fBmeroxa\-resources(1)\fP
