.nh
.TH "Meroxa" "1" "Apr 2021" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa\-open \- Open in a web browser


.SH SYNOPSIS
.PP
\fBmeroxa open [flags]\fP


.SH DESCRIPTION
.PP
Open in a web browser


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for open


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-config\fP=""
	config file (default is $HOME/meroxa.env)

.PP
\fB\-\-debug\fP[=false]
	display any debugging information

.PP
\fB\-\-json\fP[=false]
	output json


.SH SEE ALSO
.PP
\fBmeroxa(1)\fP, \fBmeroxa\-open\-billing(1)\fP
