.nh
.TH "Meroxa" "1" "Feb 2022" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa\-pipelines\-remove \- Remove pipeline


.SH SYNOPSIS
.PP
\fBmeroxa pipelines remove NAME [flags]\fP


.SH DESCRIPTION
.PP
Remove pipeline


.SH OPTIONS
.PP
\fB\-f\fP, \fB\-\-force\fP[=false]
	skip confirmation

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for remove


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-cli\-config\-file\fP=""
	meroxa configuration file

.PP
\fB\-\-debug\fP[=false]
	display any debugging information

.PP
\fB\-\-json\fP[=false]
	output json

.PP
\fB\-\-timeout\fP=10s
	set the duration of the client timeout in seconds


.SH SEE ALSO
.PP
\fBmeroxa\-pipelines(1)\fP
