.nh
.TH "Meroxa" "1" "Oct 2022" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa-whoami - Display the current logged in user


.SH SYNOPSIS
.PP
\fBmeroxa whoami [flags]\fP


.SH DESCRIPTION
.PP
Display the current logged in user


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for whoami


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--cli-config-file\fP=""
	meroxa configuration file

.PP
\fB--debug\fP[=false]
	display any debugging information

.PP
\fB--json\fP[=false]
	output json

.PP
\fB--timeout\fP=10s
	set the duration of the client timeout in seconds


.SH EXAMPLE
.PP
.RS

.nf
meroxa whoami

.fi
.RE


.SH SEE ALSO
.PP
\fBmeroxa(1)\fP
