.nh
.TH "Meroxa" "1" "Oct 2022" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa-environments-list - List environments


.SH SYNOPSIS
.PP
\fBmeroxa environments list [flags]\fP


.SH DESCRIPTION
.PP
List environments


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for list

.PP
\fB--no-headers\fP[=false]
	display output without headers


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--cli-config-file\fP=""
	meroxa configuration file

.PP
\fB--debug\fP[=false]
	display any debugging information

.PP
\fB--json\fP[=false]
	output json

.PP
\fB--timeout\fP=10s
	set the duration of the client timeout in seconds


.SH SEE ALSO
.PP
\fBmeroxa-environments(1)\fP
