.nh
.TH "Meroxa" "1" "Feb 2024" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa-secrets-create - Create a Turbine Secret


.SH SYNOPSIS
.PP
\fBmeroxa secrets create NAME --data '{}' [flags]\fP


.SH DESCRIPTION
.PP
This command will create a secret as promted by the user.'
After successful creation, the secret can be used in a connector.


.SH OPTIONS
.PP
\fB--data\fP=""
	Secret's data, passed as a JSON string

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for create


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--api-url\fP=""
	API url

.PP
\fB--cli-config-file\fP=""
	meroxa configuration file

.PP
\fB--debug\fP[=false]
	display any debugging information

.PP
\fB--json\fP[=false]
	output json

.PP
\fB--timeout\fP=10s
	set the duration of the client timeout in seconds


.SH EXAMPLE
.EX
meroxa secret create NAME
		          meroxa secret create NAME --data '{}'
		

.EE


.SH SEE ALSO
.PP
\fBmeroxa-secrets(1)\fP
