.nh
.TH "Meroxa" "1" "Sep 2021" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa\-connect \- Connect two resources together


.SH SYNOPSIS
.PP
\fBmeroxa connect \-\-from RESOURCE\-NAME \-\-to RESOURCE\-NAME [flags]\fP


.SH DESCRIPTION
.PP
Use the connect command to automatically configure the connectors required to pull data
from one resource (source) to another (destination).

.PP
This command is equivalent to creating two connectors separately,
one from the source to Meroxa and another from Meroxa to the destination:

.PP
meroxa connect \-\-from RESOURCE\-NAME \-\-to RESOURCE\-NAME \-\-input SOURCE\-INPUT \-\-pipeline my\-pipeline

.PP
or

.PP
meroxa connector create \-\-from postgres \-\-input accounts \-\-pipeline my\-pipeline # Creates source connector
meroxa connector create \-\-to redshift \-\-input orders \-\-pipeline my\-pipeline # Creates destination connector


.SH OPTIONS
.PP
\fB\-\-from\fP=""
	source resource name

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for connect

.PP
\fB\-\-input\fP=""
	command delimited list of input streams

.PP
\fB\-\-pipeline\fP=""
	pipeline name to attach connectors to

.PP
\fB\-\-to\fP=""
	destination resource name


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-config\fP=""
	config file

.PP
\fB\-\-debug\fP[=false]
	display any debugging information

.PP
\fB\-\-json\fP[=false]
	output json

.PP
\fB\-\-timeout\fP=10s
	set the duration of the client timeout in seconds (default 10s)


.SH SEE ALSO
.PP
\fBmeroxa(1)\fP
