.nh
.TH "Meroxa" "1" "Apr 2021" "Meroxa CLI " "Meroxa Manual"

.SH NAME
.PP
meroxa\-update \- Update a component


.SH SYNOPSIS
.PP
\fBmeroxa update [flags]\fP


.SH DESCRIPTION
.PP
Update a component of the Meroxa platform, including connectors


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for update


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-config\fP=""
	config file (default is $HOME/meroxa.env)

.PP
\fB\-\-debug\fP[=false]
	display any debugging information

.PP
\fB\-\-json\fP[=false]
	output json


.SH SEE ALSO
.PP
\fBmeroxa(1)\fP, \fBmeroxa\-update\-connector(1)\fP, \fBmeroxa\-update\-pipeline(1)\fP, \fBmeroxa\-update\-resource(1)\fP
