// Code generated by MockGen. DO NOT EDIT.
// Source: cmd/remove_connector.go

// Package mock_cmd is a generated GoMock package.
package mock_cmd

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	meroxa "github.com/meroxa/meroxa-go"
)

// MockRemoveConnectorClient is a mock of RemoveConnectorClient interface.
type MockRemoveConnectorClient struct {
	ctrl     *gomock.Controller
	recorder *MockRemoveConnectorClientMockRecorder
}

// MockRemoveConnectorClientMockRecorder is the mock recorder for MockRemoveConnectorClient.
type MockRemoveConnectorClientMockRecorder struct {
	mock *MockRemoveConnectorClient
}

// NewMockRemoveConnectorClient creates a new mock instance.
func NewMockRemoveConnectorClient(ctrl *gomock.Controller) *MockRemoveConnectorClient {
	mock := &MockRemoveConnectorClient{ctrl: ctrl}
	mock.recorder = &MockRemoveConnectorClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoveConnectorClient) EXPECT() *MockRemoveConnectorClientMockRecorder {
	return m.recorder
}

// DeleteConnector mocks base method.
func (m *MockRemoveConnectorClient) DeleteConnector(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConnector", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteConnector indicates an expected call of DeleteConnector.
func (mr *MockRemoveConnectorClientMockRecorder) DeleteConnector(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConnector", reflect.TypeOf((*MockRemoveConnectorClient)(nil).DeleteConnector), ctx, id)
}

// GetConnectorByName mocks base method.
func (m *MockRemoveConnectorClient) GetConnectorByName(ctx context.Context, name string) (*meroxa.Connector, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectorByName", ctx, name)
	ret0, _ := ret[0].(*meroxa.Connector)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnectorByName indicates an expected call of GetConnectorByName.
func (mr *MockRemoveConnectorClientMockRecorder) GetConnectorByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectorByName", reflect.TypeOf((*MockRemoveConnectorClient)(nil).GetConnectorByName), ctx, name)
}
