name: CI
on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.20
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Build
      run: |
       make build
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.20
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout 4m0s
  vet:
    name: Vet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Vet
        run: go vet ./...
  test:
    name: Test
    needs: [ build ]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.20
      - name: Generated files
        run: |
          brew install mockery@v2.35.2
          export PATH=$PATH:$(go env GOPATH)/bin
          make generate fmt
          git diff --exit-code --numstat
      - name: Run tests
        run: |
         make test
        env:
         GOPATH: /home/runner/work/cli/go
