name: CI
on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache-dependency-path: 'go.sum'
    - name: Build
      run: |
       make build
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          args: --timeout 4m0s
  vet:
    name: Vet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: Vet
        run: go vet ./...
  test:
    name: Test
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: Generated files
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          make generate fmt
          git diff --exit-code --numstat
      - name: Run tests
        run: |
         make test
        env:
         GOPATH: /home/runner/work/cli/go
