name: CI
on:
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.18
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Build
      run: |
       make build
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.18
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout 4m0s
  vet:
    name: Vet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Vet
        run: go vet ./...
  test:
    name: Test
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.18
      - name: Run tests
        run: |
         make test
        env:
         GOPATH: /home/runner/work/cli/go
  turbinetest:
    name: Turbine Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.18
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: |
          xdg-settings set default-web-browser google-chrome.desktop
          xdg-mime default google-chrome.desktop 'x-scheme-handler/http'
          xdg-mime default google-chrome.desktop 'x-scheme-handler/https'
          xdg-mime default google-chrome.desktop 'text/html'
      - run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - uses: actions/checkout@v3
        with:
          path: cli
      - uses: actions/checkout@v3
        with:
          repository: jmar910/turbine-integration
          path: turbine-integration
          ref: james/debug-2-electric-boogaloo
      - name: Install CLI
        run: |
          cd cli
          make install
        env:
         GOPATH: /home/runner/go
      - name: Node Dependencies
        run: |
          cd turbine-integration
          npm install
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm test
          working-directory: ./turbine-integration
        env:
         GOPATH: /home/runner/go


