name: Acceptance Test

# Run this workflow every time a new PR wants to merge to master/main
on:
  pull_request:
    branches:
      - master
      - main
  push:
jobs:
  acceptance:
    name: Acceptance Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        enable_data_plane: [true]
    steps:
      - name: Checkout Acceptance
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MEROXA_MACHINE }}
          repository: meroxa/acceptance
          path: acceptance
      # Note: the following folder layout matters for platform-dev-setup:
      # parent_dir:
      #   - meroxa
      #   - merman
      #   - platform-dev-setup
      - name: Checkout CLI
        uses: actions/checkout@v2
        with:
          path: ./acceptance/cli
      - name: Checkout Platform API
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MEROXA_MACHINE }}
          repository: meroxa/platform-api
          path: meroxa
      - name: Checkout Merman
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MEROXA_MACHINE }}
          repository: meroxa/merman
          path: merman
      - name: Checkout Logan
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MEROXA_MACHINE }}
          repository: meroxa/logan
          path: logan
      - name: Checkout platform-dev-setup
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MEROXA_MACHINE }}
          repository: meroxa/platform-dev-setup
          path: platform-dev-setup
      # Download minikube
      - name: Download minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          echo "MINIKUBE_VERSION=$(minikube version -o json | jq -r '.minikubeVersion')" >> $GITHUB_ENV
      - name: Cache minikube images
        uses: actions/cache@v2
        with:
          path: /home/runner/.minikube/cache
          key: minikube-cache-${{ runner.os }}-${{ env.MINIKUBE_VERSION }}
      
      # Set up control plane & data plane
      # This should already push the current API code to minikube
      - name: Setup control plane & data plane
        working-directory: ./platform-dev-setup
        run: ENABLE_DATA_PLANE=${{ matrix.enable_data_plane }} make

      # Run acceptance tests
      - name: Run acceptance tests
        working-directory: ./acceptance
        run: |
          MINIKUBE_API_HOST="$(minikube service -n meroxa-nginx meroxa-nginx-ingress-nginx-controller --url --profile meroxa-control-plane | head -n 1)"
          # FIXME: the test PG in the data plane can't be accessed from the control plane with the minikube Docker driver
          # Using a public accessible RDS for now
          MINIKUBE_PG_URL="${{ secrets.TEST_DB_URL }}" 
          docker build -t meroxa/acceptance --build-arg=CLI_PATH=./cli .
          docker run --network host meroxa/acceptance -test.v -postgres-url $MINIKUBE_PG_URL -api-host $MINIKUBE_API_HOST