name: Velocity Workflow
on:
  pull_request:
    types: [opened, closed]
jobs:
  metrics:
    if: |
      (github.event.action == 'closed' &&
      github.event.pull_request.merged == true) ||
      github.event.action == 'opened'
    name: Track merge request activity
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      # Optional step that allows tagging time to merge with a team
      - uses: tspascoal/get-user-teams-membership@v1
        id: actorTeams
        if: ${{ !endsWith(github.event.pull_request.user.login, '[bot]') }}
        with:
          username: ${{ github.event.pull_request.user.login }}
          GITHUB_TOKEN: ${{ secrets.MEROXA_MACHINE }}

      - id: datadog-metrics
        uses: scribd/github-action-datadog-reporting@v1
        with:
          datadog-metric-prefix: 'github_action_reporting.repo_velocity'
          metrics-type: 'velocity'
          teams: ${{ steps.actorTeams.outputs.teams }}
        env:
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          OCTOKIT_TOKEN: ${{ secrets.MEROXA_MACHINE }}
          